export default {
  root: "/",
  login: "/login",
  signup: "/signup",
  allEmployees: "/AllEmployees",
  addEmployee: "/AddEmployee",
  employeeProfile: "/employeeProfile",
  itEmployeePage: "/IT/AllEmployees",
  addAccount: "/IT/addaccount",
  createOrderPage: "/createOrder",
  ViewAllOrdersPage: "/ViewAllOrders",
  ViewSingleOrderPage: "/ViewSingleOrder",
  ViewAllItems: "/ViewAllItems",
  viewCustomers: "/viewCustomers",
  AddCustomer: "/AddCustomer",
  AddSupplier: "/AddSupplier",
  ViewOrdersFinance: "/ViewOrdersFinance",
  ViewOrdersLogistics: "/ViewOrdersLogistics",
  ViewOrdersInventory: "/ViewOrdersInventory",
  CategoriesInventoryPage: "/CategoriesInventory",
  ViewSingleItemPage: "/ViewSingleItem"
}