export default {
  root: "/",
  login: "/login",
  signup: "/signup",
  allEmployees: "/AllEmployees",
  addEmployee: "/AddEmployee",
  employeeProfile: "/employeeProfile",
  itEmployeePage: "/IT/AllEmployees",
  addAccount: "/IT/addaccount",
  createOrderPage: "/createOrder",
  ViewAllOrdersPage: "/ViewAllOrders",
  ViewSingleOrderPage: "/ViewSingleOrder",
  ViewAllItems: "/ViewAllItems",
  viewCustomers: "/viewCustomers",
  viewSuppliers: "/viewSuppliers",

  AddCustomer: "/AddCustomer",
  AddSupplier: "/AddSupplier",
  ViewOrdersFinance: "/ViewOrdersFinance",
  ViewOrdersLogistics: "/ViewOrdersLogistics",
  ViewPurchaseOrdersLogistics: '/ViewPurchaseOrderLogistics',
  ViewOrdersInventory: "/ViewOrdersInventory",
  CategoriesInventoryPage: "/CategoriesInventory",
  ViewSingleItemPage: "/ViewSingleItem",
  AddMasterDataPage: "/AddMasterDataPage",
  ViewAllMasterData: "/ViewAllMasterData",
  SivPage: "/SivPage",
  CreatePurchaseOrder: "/CreatePurchaseOrder",
  ViewAllPurchaseOrder: "/ViewAllPurchaseOrder",
  ViewSinglePurchaseOrder: "/ViewSinglePurchaseOrder",
  SupplierInvoice: "/SupplierInvoice",
  ViewPurchasedItems: '/ViewPurchasedItems'

};

